language: c
compiler:
  - gcc
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison libcurl4-openssl-dev libhiredis-dev libmarkdown2-dev libapr1-dev libaprutil1-dev apache2 libcap-dev
env:
  #
  # VhostMaxClients TEST
  #
  # for apache2.4.x with event
  - HTTPD_VERSION=httpd-2.4.46
    HTTPD_CONFIG_OPT="--with-mpm=event"
    APR=apr-1.7.0
    APR_UTIL=apr-util-1.6.1
    HTTPD_TAR=${HTTPD_VERSION}.tar.gz
    APR_TAR=${APR}.tar.gz
    APR_UTIL_TAR=${APR_UTIL}.tar.gz
    APXS_CHECK_CMD="./${HTTPD_VERSION}/apache/bin/apachectl -v"
    VHOST_CONF="conf/mod_vhost_maxclients.conf.2.4"
  # for apache2.4.x with worker
  - HTTPD_VERSION=httpd-2.4.46
    HTTPD_CONFIG_OPT="--with-mpm=worker"
    APR=apr-1.7.0
    APR_UTIL=apr-util-1.6.1
    HTTPD_TAR=${HTTPD_VERSION}.tar.gz
    APR_TAR=${APR}.tar.gz
    APR_UTIL_TAR=${APR_UTIL}.tar.gz
    APXS_CHECK_CMD="./${HTTPD_VERSION}/apache/bin/apachectl -v"
    VHOST_CONF="conf/mod_vhost_maxclients.conf.2.4"
  # for apache2.4.x with prefork
  - HTTPD_VERSION=httpd-2.4.46
    HTTPD_CONFIG_OPT="--with-mpm=prefork"
    APR=apr-1.7.0
    APR_UTIL=apr-util-1.6.1
    HTTPD_TAR=${HTTPD_VERSION}.tar.gz
    APR_TAR=${APR}.tar.gz
    APR_UTIL_TAR=${APR_UTIL}.tar.gz
    APXS_CHECK_CMD="./${HTTPD_VERSION}/apache/bin/apachectl -v"
    VHOST_CONF="conf/mod_vhost_maxclients.conf.2.4.prefork"
  #
  # VhostMaxClientsPerIP TEST
  #
  # for apache2.4.x with event
  - HTTPD_VERSION=httpd-2.4.46
    HTTPD_CONFIG_OPT="--with-mpm=event"
    APR=apr-1.7.0
    APR_UTIL=apr-util-1.6.1
    HTTPD_TAR=${HTTPD_VERSION}.tar.gz
    APR_TAR=${APR}.tar.gz
    APR_UTIL_TAR=${APR_UTIL}.tar.gz
    APXS_CHECK_CMD="./${HTTPD_VERSION}/apache/bin/apachectl -v"
    VHOST_CONF="conf/mod_vhost_maxclients_per_ip.conf.2.4"
  # for apache2.4.x with worker
  - HTTPD_VERSION=httpd-2.4.46
    HTTPD_CONFIG_OPT="--with-mpm=worker"
    APR=apr-1.7.0
    APR_UTIL=apr-util-1.6.1
    HTTPD_TAR=${HTTPD_VERSION}.tar.gz
    APR_TAR=${APR}.tar.gz
    APR_UTIL_TAR=${APR_UTIL}.tar.gz
    APXS_CHECK_CMD="./${HTTPD_VERSION}/apache/bin/apachectl -v"
    VHOST_CONF="conf/mod_vhost_maxclients_per_ip.conf.2.4"
  # for apache2.4.x with prefork
  - HTTPD_VERSION=httpd-2.4.46
    HTTPD_CONFIG_OPT="--with-mpm=prefork"
    APR=apr-1.7.0
    APR_UTIL=apr-util-1.6.1
    HTTPD_TAR=${HTTPD_VERSION}.tar.gz
    APR_TAR=${APR}.tar.gz
    APR_UTIL_TAR=${APR_UTIL}.tar.gz
    APXS_CHECK_CMD="./${HTTPD_VERSION}/apache/bin/apachectl -v"
    VHOST_CONF="conf/mod_vhost_maxclients_per_ip.conf.2.4.prefork"
script:
  - make -e test
